### ISSUE TITLE
ESE demo

### ISSUE THREAD

**Issue by vstirbu** [CompliancePal/modelcard-action#29]
## Objective

Demonstrate the model card document validation using the default and custom rulesets.

## Prerequisite

1. ML project repository
2. GitHub action configured to run the modelcard validation action
3. Custom ruleset in the ML project repository

## Script

1. Create a new branch
4. Commit a model card document with two properties that fail default and custom validation
5. Show the failed check result 
6. Fix the model card properties according to the rulesets
7. Push new commit with the fixes
8. Show the passed check result

**Comment by myzozoz** [comment]
Demo was held
