### ISSUE TITLE
Test model card document

### ISSUE THREAD

**Issue by vstirbu** [CompliancePal/modelcard-action#9]
Define a test model card document scenario based on an example from Google's [model cards](https://modelcards.withgoogle.com/model-reports) site.

**Comment by myzozoz** [comment]
The test document [modelcardexample.yaml](https://github.com/CompliancePal/modelcard-actions-dummy/blob/main/modelcardexample.yaml) can be found in the repository https://github.com/CompliancePal/modelcard-actions-dummy
